name: CI

on: [push, pull_request]

jobs:
  test-src:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v2
      - uses: rome/setup-rome@v0.4
        with:
          version: latest
      - name: Cache `~/.npm`
        uses: actions/cache@v2
        env:
          cache-name: cache-npm-cache
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on by default
          key: ${{ env.cache-name }}-${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
      - name: Use `node` v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: make test-spec-with-coverage
      - run: make lint-ci
      - run: make test-src-tsc
      - run: make test-src-internal-import-restrictions
      - run: make test-src-does-not-import-dist
      - run: make test-src-scripts-consistency
      - run: make format # note: not in `test-src` in `package.json`, only in CI
      - run: make clean

  test-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Cache `~/.npm`
        uses: actions/cache@v2
        env:
          cache-name: cache-npm-cache
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on by default
          key: ${{ env.cache-name }}-${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
      - name: Use `node` v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: make build-esm
      - run: make build-bin
      - run: make build-types
      - run: make build-sites
      - run: make build-site-docs
      - run: make clean

  test-dist:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Cache `~/.npm` # Only for the `test-dist` job.
        uses: actions/cache@v2
        env:
          cache-name: cache-npm-cache
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on by default
          key: ${{ env.cache-name }}-${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
      - name: Cache ~/.cache/ms-playwright
        uses: actions/cache@v2
        env:
          cache-name: cache-npm-cache
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on by default
          key: ${{ env.cache-name }}-${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
      - name: Use `node` v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: make build-esm
      - run: make test-dist-esm-node-import
      - run: make test-dist-esm-perf
      - run: make test-dist-esm-plain-esbuild-compat
      - run: make test-dist-esm-scramble-all-events
      - run: make test-dist-esm-vite
      - run: make test-dist-esm-build-size
      - run: make build-sites
      - run: make test-dist-sites-experiments
      - run: make clean
