name: js.cubing.net

on:
  push:
    branches: [main]

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-pages:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Cache `~/.npm`
        uses: actions/cache@v3
        env:
          cache-name: cache-npm-cache
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on by default
          key: ${{ env.cache-name }}-${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
      - name: Use `node` v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: make build-site-docs
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist/sites/js.cubing.net/
          retention-days: 1

  deploy-pages:
    runs-on: ubuntu-latest

    needs: build-pages

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    # https://github.com/actions/deploy-pages#usage
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
